name: georgia-connects-admin-frontend
static_sites:
  - name: admin-frontend
    source_dir: /
    github:
      repo: ADartsmelia/georgia-connects-hub
      branch: main
    build_command: cd georgia-connects-hub-admin && npm install && npm run build
    output_dir: georgia-connects-hub-admin/dist
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.networkinggeorgia.com/api/v1
      - key: VITE_SOCKET_URL
        value: https://api.networkinggeorgia.com
